### ISSUE TITLE
Streamlink-Service on Synology DSM 7.2

### ISSUE THREAD

**Issue by srinath1965** [vstavrinov/streamlink-service#5]
I am running the streamlink Service - vstavrinov/streamlink-service:latest image on a Synology DSM 7.2, which I installed using the Synology Container Manager. I am trying to view the output of a youtube live stream using the streamlink service (Eg. http://localhost:8000/?youtube.com/@SkyNews/live+best=) on a media client such as VLC. When I have only a single VLC client, the system runs OK and I am able to see the output in VLC. However, when I connect to a second VLC client simultaneously, after about 10 min, the streamlink-service stops transmitting the media stream to either VLC client and the service needs to be restarted for either client to recieve the media stream. I have looked at the Synology Log viewer and dont see any entries regarding the streamlink-service.  So, there is little debuging information available.

Can the developer reproduce this problem? If not, Please tell me how to enable logging within the streamlink Service (or where it is maintained in Synology DSM 7.2), so that I can retrieve the logs

Thanks
Srinath

**Comment by vstavrinov** [comment]
You are right - vague problem exists. I will see later.

**Comment by vstavrinov** [comment]
fixed.

**Comment by srinath1965** [comment]
Hi Vlad -

Problem is still there. I imported the latest image earlier today via container manager and ran the Stream-link service. I was running 2 clients to connect to the service - one VLC client from my PC and another IPTV Player (TIVIMATE) on my TV. The feed froze after 10 min (exactly as before). I have added screenshots of my container manager statistics and logs (just in case it helps you). 

Thanks
Srinath

![Image](https://github.com/user-attachments/assets/da30e471-3768-4dbe-86dc-9406e10e17f9)
![Image](https://github.com/user-attachments/assets/0f032043-026a-432a-9b41-075fd69d7c19)
![Image](https://github.com/user-attachments/assets/00b5442a-bf3f-4daf-a949-c84b65addbaa)

**Comment by vstavrinov** [comment]
You are using old image. To update it do the following in that order:

1. Read README file.
2. Stop container.
3. Remove container.
4. Remove image.
5. Run container.

P.S. Vlad is shorthand for Vladislav not Vladimir

**Comment by srinath1965** [comment]
Hi - The Streamlink service looks good now. I have been running two client sessions without a problem for an hour. I am going to close this thread

Thanks a lot for your support. This is a very useful utility

**Comment by srinath1965** [comment]
Hi Vladimir -

Can you provide the link to the streamlink-service image on Jun 13, that
you had provided earlier?

**Comment by vstavrinov** [comment]
https://github.com/vstavrinov/streamlink-service/pkgs/container/streamlink-service/versions

Click any version to see the date

**Comment by vstavrinov** [comment]
version 2.1.0 at Jun 12  that is where the problem was fixed.  In all next versions  only streamlink itself was updated:

https://github.com/vstavrinov/streamlink-service/pkgs/container/streamlink-service/437115575?tag=2.1.0

**Comment by vstavrinov** [comment]
Or use docker hub as usual

`docker pull vstavrinov/streamlink-service:2.1.0`

**Comment by srinath1965** [comment]
Thanks. I did that and was able to retrieve the image and run it
